# Generated by Django 5.0.2 on 2024-03-13 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iotData', '0002_iotdata_password_iotdata_salinity_iotdata_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iotdata',
            old_name='salinity',
            new_name='dissolved_oxygen',
        ),
    ]
