# Generated by Django 5.0.2 on 2024-03-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotData', '0003_contactformsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotdata',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
