# Generated by Django 5.0.2 on 2024-03-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iotData", "0003_rename_salinity_iotdata_dissolved_oxygen"),
        ("iotData", "0004_alter_iotdata_password"),
    ]

    operations = []
