# Generated by Django 5.0.2 on 2024-03-13 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iotData', '0005_merge_20240313_1502'),
        ('iotData', '0005_merge_20240313_2037'),
    ]

    operations = [
    ]
